### ISSUE TITLE
TDLib can't be initialized

### ISSUE THREAD

**Issue by DerBunteBall** [Xumeiquer/tmd#2]
Hi,

I'm always getting this:

```
2025/01/23 20:11:18 ERROR found an error while initializing a TDLib NewClient msg="500 Request aborted"
```

My Docker CLI looks like this:

```
docker run --rm -it -v ./tmd.yml:/etc/tmd/tmd.yml:ro -v ./data:/data/ ghcr.io/xumeiquer/tmd list
```

My Config like this:

```yml
tdlib:
  path: "/data/"
  api:
    id: app_id
    hash: "app_hash"
  files:
    path: "/data/files/"
  database:
    path: "/data/db/"
    secret: "some_alphanumeric_secret"
  log:
    to:
    level:
```

I guess I configured something wrong.

1. What's the "path" key on sublevel of tdlib. I guess the workpath not the binpath
2. Does the "path" which is a child of "database" a absolute file path or a dir path?

Best Regards
